<?php

/**
 * @file
 * Module file for the Muut comments module.
 */

/**
 * Implements hook_menu().
 */
function muut_comments_menu() {
  $items = array();

  $items['muut-comments/auth'] = array(
    'title' => 'Muut authentication',
    'description' => 'Authentication callback for Muut comments.',
    'page callback' => 'muut_comments_auth_callback',
    'access callback' => 'muut_comments_access_callback',
    'delivery callback' => 'drupal_json_output',
  );

  $items['admin/config/system/muut_comments'] = array(
    'title' => 'Muut comments',
    'description' => 'Configure Muut comments.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('muut_comments_config_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'muut_comments.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Custom ajax callback for muut comments.
 *
 * @return @array
 *   Returns data structure with sso data.
 */
function muut_comments_auth_callback() {

  $apikey = variable_get('muut_comments_api_key', '');
  $secretkey = variable_get('muut_comments_api_secret', '');
  $timestamp = time();

  // Data for the anonymous user.
  $data = array('user' => array());

  if (user_is_logged_in() && user_access('post muut comments')) {
    $user = user_uid_optional_load();

    $displayname = $user->name;
    // Fallback to username.
    $displayname_field = variable_get('muut_comments_displayname_field', FALSE);
    if ($displayname_field) {
      $items = field_get_items('user', $user, $displayname_field);
      if ($items) {
        $item = array_shift($items);
        $displayname = $item['value'];
      }
    }

    $data['user'] = array(
      "id" => $user->name,
      "displayname" => $displayname,
      "email" => $user->mail,
      // "avatar" => '',
      "is_admin" => FALSE,
    );
  }

  $message = base64_encode(json_encode($data));
  $signature = sha1($secretkey . ' ' . $message . ' ' . $timestamp);

  $result = array(
    'api' => array(
      'key' => $apikey,
      'message' => $message,
      'signature' => $signature,
      'timestamp' => $timestamp,
    ),
  );

  return $result;

}

/**
 * Custom access callback.
 *
 * @return bool
 *   Always return TRUE
 */
function muut_comments_access_callback() {
  return TRUE;
}

/**
 * Implements hook_permission().
 */
function muut_comments_permission() {
  return array(
    'post muut comments' => array(
      'title' => t('Post Muut comments'),
    ),
    'administer muut comments' => array(
      'title' => t('Administer Muut comments'),
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function muut_comments_block_info() {
  return array(
    'comments' => array(
      'info' => t('Muut comments'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function muut_comments_block_view($delta = '') {
  $block = array();

  if ($delta == 'comments') {

    // Todo: this should be exposed as an alter function.
    $ogc = og_context();
    $node = menu_get_object();
    if ($node && $node->nid) {
      $comment_id = $ogc['gid'] . ':' . $node->nid;
    }
    else {
      return;
    }

    $community_name = variable_get('muut_comments_community_name', '');

    $js_settings = array(
      'data' => array(
        'muut_comments' => array(
          'login_url' => $GLOBALS['base_url'] . '/user',
          'url' => 'https://muut.com/i/' . $community_name . '/comments/' . $comment_id,
          'show_online' => TRUE,
          'upload' => FALSE)),
      'type' => 'setting',
    );

    $block['content'] = array(
      '#markup' => '<div id="muut-comments"></div>',
      '#attached' => array(
        'js' => array(
          array('data' => '//cdn.muut.com/1/moot.da.min.js', 'type' => 'external'),
          drupal_get_path('module', 'muut_comments') . '/js/muut-comments.js',
          $js_settings,
        ),
        'css' => array(array('data' => '//cdn.muut.com/1/moot.css', 'type' => 'external')),
      ),
    );
  }

  return $block;
}
